### ISSUE TITLE
Implement prettier

### ISSUE THREAD

**Issue by raygesualdo** [3Blades/react-frontend#119]
Now that [Prettier](https://github.com/prettier/prettier) has matured, we should revisit implementing it for our codebase. It abstracts away the cognitive burden of code formatting. Plugins are available for all major IDEs that will accelerate developer speed as well. 

Included in this issue would be re-evaluating our current eslint settings as well. They may not be completely compatible with prettier. This needs to happen anyway since we're already deviating from AirBnB's styleguide but haven't formally codified what the deviations are. We may need to dump AirBnB's styleguide completely and build up our own. Not sure yet until we get into it.

- [x] Install prettier
- [x] Add prettier to lint-staged process
- [x] Reconfigure eslint settings

**Comment by johngriebel** [comment]
@raygesualdo What's the status of this?

**Comment by raygesualdo** [comment]
Not yet started. But I very much want to get this worked in in the next month or so.
