### ISSUE TITLE
Resource Endpoint Not found after creating and starting resource

### ISSUE THREAD

**Issue by roachmd** [3Blades/react-frontend#122]
## General Support

Gif Recording
![3blades_resource](https://user-images.githubusercontent.com/5784681/27746247-75419e8e-5d94-11e7-865e-715cac1bdaa9.gif)

**Comment by raygesualdo** [comment]
It seems that the value being returned from the API doesn't have the correct URL assigned. That link is driven directly but what is returned from the API.

**Comment by raygesualdo** [comment]
I'm having similar but different problems with the URLs being returned by the staging API. Would be best to open up a discussion in 3blades/app-backend as the frontend has no control over those links.

**Comment by raygesualdo** [comment]
I'm going to close this issue since there's no action items.
