### ISSUE TITLE
Enhancements to current styling workflow

### ISSUE THREAD

**Issue by raygesualdo** [3Blades/react-frontend#13]
Currently, the application uses SASS for styling, requires specific Bootstrap files for layout and forms, and no explicit class name convention. As the application scales out, I believe it would be helpful to integrate additional paradigms into the styling workflow to ensure maintainability and developer sanity. There are various ways we can do this. I have included two such options below.

### [CSS Modules](https://github.com/css-modules/css-modules)

> A CSS Module is a CSS file in which all class names and animation names are scoped locally by default.

**Pros**

1. Allows us to use almost all SCSS as it stands right now
1. Supports the full range of CSS
1. Enables collocation of style file and component file
1. Removes the need for an explicit naming convention
1. Limits scope of CSS to single component

**Cons**

1. Requires change to Webpack config (CSS modules are not supported by create-react-app)

### [styled-components](https://github.com/styled-components/styled-components)

> Visual primitives for the component age

**Pros**

1. Supports the full range of CSS
1. Porting SASS/CSS is fairly straightforward
1. Allows for declarative styling based on props
1. Enables collocation of styles _within_ the component file
1. Supports both React and React Native
1. Has runtime theme support
1. No build process changes necessary

**Cons**

1. Ties us to a 3rd-party implementation for UI components

I have used both of these methods in production before and they each work very well. I tend to lean toward `styled-components` because of its closer adherence to React's declarative and componentized model. I gave a talk on these a few weeks back and can run through it if it would be helpful. Thoughts @captainsafia and @AbhishikthaReddy?

**Comment by raygesualdo** [comment]
I wanted to provide examples of what this would look like. Let's start with an example with CSS Modules.

```scss
// src/component/layout/vertical-navigation.scss
@import '../../styles/variables.scss';

.vertical-nav-menu {
    list-style-type: none;
    margin: 0;
    padding: 0; font-size: 1.1em;
}
```
```javascript
// src/component/layout/vertical-navigation.js
import React from 'react';
import * as Material from 'react-icons/lib/md';
import NavigationLink from './navigation-link';
import styles from './vertical-navigation.scss'

class VerticalNavigation extends React.Component {
  render() {
    const { userName, projectId } = this.props;
    return (
      <div>
        <ul className={styles.verticalNavMenu}> // snake-case to camelCase automatically
           // ...
        </ul>
      </div>
    );
  }
}

export default VerticalNavigation;
```
```sass
// src/component/layout/navigation-link.scss
@import '../../styles/variables.scss';

.item {
  padding: 5px;
  padding-left: 10px;
  &:hover {
    background-color: $cloud-gray;
  }
  &.active {
    background-color: rgba(88, 178, 8, 0.5);
  }
}

.link {
  display: inline-block;
  margin-left: 10px;
  width: 60px;
  color: inherit;
  text-decoration: none;
}
```
```javascript
// src/component/layout/navigation-link.js
import React from 'react';
import { Link, IndexLink } from 'react-router';
import styles from './navigation-link.scss';

class NavigationLink extends React.Component {
  // ...

  render() {
    // ...

    return (
      <li className={`${styles.item} ${isActive ? styles.active : ''}`}>
        <IconComponent/>
        <LinkComponent to={to} className={styles.link>
          {children}
        </LinkComponent>
      </li>
    );
  }
}

export default NavigationLink;
```

**Comment by raygesualdo** [comment]
Now for styled-components.
```javascript
// src/component/layout/vertical-navigation.js
import React from 'react';
import * as Material from 'react-icons/lib/md';
import NavigationLink from './navigation-link';
import styled from 'styled-components';

const VerticalNavMenu = styled.ul`
  list-style-type: none;
  margin: 0;
  padding: 0; font-size: 1.1em;
`;

class VerticalNavigation extends React.Component {
  render() {
    const { userName, projectId } = this.props;
    return (
      <div>
        <VerticalNavMenu>
           // ...
        </VerticalNavMenu>
      </div>
    );
  }
}

export default VerticalNavigation;
```
```javascript
// src/component/layout/navigation-link.js
import React from 'react';
import { Link, IndexLink } from 'react-router';
import styled from 'styled-components';

const ListItem = styled.li`
  padding: 5px;
  padding-left: 10px;
  ${props => props.active && 'background-color: rgba(88, 178, 8, 0.5);'}
  &:hover {
    background-color: $cloud-gray;
  }
`;

class NavigationLink extends React.Component {
  // ...

  render() {
    // ...
    const LinkComponent = styled(index ? Link : IndexLink)`
      display: inline-block;
      margin-left: 10px;
      width: 60px;
      color: inherit;
      text-decoration: none;
    `;

    return (
      <ListItem active={isActive}>
        <IconComponent/>
        <LinkComponent to={to}>
          {children}
        </LinkComponent>
      </ListItem>
    );
  }
}

export default NavigationLink;
```

**Comment by raygesualdo** [comment]
Another avenue I want us to be aware of - regardless of the style workflow we choose - is the possibility of breaking out our UI elements into their own repo. This would allow even more decoupled development of UI elements separate from the application logic. This is not a step I would recommend in the short term due to the additional overhead of maintaining both. I wanted to throw the idea out there though and get some feedback.

**Comment by jgwerner** [comment]
@raygesualdo the above seems like an interesting option. This could give our potential users the opportunity to add their own styling elements to our front end app. styling elements should be relatively static, so having them in their own folder for now seems like it would do the trick.
