### ISSUE TITLE
Tooling to enforce commit and PR conventions

### ISSUE THREAD

**Issue by raygesualdo** [3Blades/react-frontend#14]
It would be helpful to automate the enforcement of commit and PR conventions. Here is an initial list of tasks that could be automated:

* Make sure commit message follow convention at commit time
* Make sure commit message follow convention at PR time
* Enforce signing the most recent commit in a PR

What other tasks could/should we add?

I don't have much experience in this area but here are a few tools I found to help with this.

* [DangerJS](https://github.com/danger/danger-js)
* [husky](https://www.npmjs.com/package/husky)
* [validate-commit-msg](https://github.com/kentcdodds/validate-commit-msg)

/cc @captainsafia @AbhishikthaReddy

**Comment by jgwerner** [comment]
@raygesualdo This can be done manually for now. If we `squash` commits before merge then the last commit would be the singing commit anyway. We could revisit this later once we have more commits to handle.
