### ISSUE TITLE
API mocking frameworks

### ISSUE THREAD

**Issue by raygesualdo** [3Blades/react-frontend#15]
When we get to the point of integrating with the API, it would be best to not have to have the full backend server running on the developer's local machine. To that end, it would be good to look into Node.js-based modules that would mock the API for us, both during development and testing. Below is a sampling of possible solutions.

* [service-mocker](https://github.com/service-mocker/service-mocker)
* [json-server](https://github.com/typicode/json-server)
* [mock-node](https://github.com/ianunay/mock-node)
* [node-mock-server](https://github.com/smollweide/node-mock-server)
* [swagger-server](https://github.com/BigstickCarpet/swagger-server)
* [swagger-mock-api](https://github.com/dzdrazil/swagger-mock-api)

Ideally, the mock server we pick would consume a Swagger file. This way, we can easily keep the mock server and the backend application in sync.

/cc @captainsafia @AbhishikthaReddy

**Comment by jgwerner** [comment]
@raygesualdo my vote is to stick with swagger, since django is publishing swagger.json with restful add on.

**Comment by johngriebel** [comment]
Closing, old and irrelevant at this point.
