### ISSUE TITLE
Change URLs to Account for Refactoring of Environment Resources

### ISSUE THREAD

**Issue by johngriebel** [3Blades/react-frontend#193]
In [app-backend/275](https://github.com/3Blades/app-backend/issues/275), the EnvironmentResources model and related endpoints were renamed to ServerSize. This results in an issue where users can not define a new server, as they can't access the ServerSize options:
![image](https://user-images.githubusercontent.com/5742121/29024034-349aca46-7b3e-11e7-8d28-681cfca40acf.png)

![image](https://user-images.githubusercontent.com/5742121/29024077-5b86d366-7b3e-11e7-9b11-6af2112b1fd0.png)

The URL `dev-api.3blades.ai/v1/admin/servers/options/resources/` should now be 
`dev-api.3blades.ai/v1/servers/options/server-size/`.

The updated endpoint definitions were included in [openapi/98](https://github.com/3Blades/openapi/pull/98).  Note that server sizes are global, and should no longer be namespaced.

**Comment by jgwerner** [comment]
@johngriebel the URL should include admin? If that is the case we need to modify swagger spec.

**Comment by johngriebel** [comment]
@jgwerner no, it shouldn't. Good catch. I'll change the issue and verify that app-backend is serving the correct URL.
