### ISSUE TITLE
Dev & Demo -- Cannot Delete Resource or Project

### ISSUE THREAD

**Issue by roachmd** [3Blades/react-frontend#211]
I've tested in both Dev and Demo under the apitester users.

Deleting a resource and Project seem to be broken.

**Comment by roachmd** [comment]
Check the backend through Swagger and verified the APi endpoint were working.

**Comment by raygesualdo** [comment]
Seems to be an issue in 3blades/app-backend.

**Comment by roachmd** [comment]
Closing Issue. Verified via swagger this is not a front end issue.
