### ISSUE TITLE
Clarify Deleting and Terminating Servers

### ISSUE THREAD

**Issue by johngriebel** [3Blades/react-frontend#212]
![screen shot 2017-08-29 at 12 24 38 pm](https://user-images.githubusercontent.com/5742121/29832325-d215a358-8cb5-11e7-8ef7-8096a0775849.png)
Currently, as seen in the attached screenshot, users can "delete" a server using the button. In actuality, this _terminates_ a server. A recent change in app-backend modified server termination so that the object is no longer delete from the database.

As a result, the current Delete button should be renamed to Terminate, and a new button that actually deletes the server from the database should be added.

**Comment by raygesualdo** [comment]
@johngriebel is `terminate` the same as `stop`?

**Comment by johngriebel** [comment]
@raygesualdo I believe that is the case for now. I think that may change when we move to Docker swarm though. To delete a server we can just send `DELETE` to the server's detail endpoint
