### ISSUE TITLE
Update codeclimate config

### ISSUE THREAD

**Issue by raygesualdo** [3Blades/react-frontend#22]
The repo isn't set up in such a way that codeclimate can accurately provide feedback. The codeclimate admin app alerted me to this. [As best as I can find](https://docs.codeclimate.com/docs/eslint), this is because the repo is missing a `.eslintrc` file.

**Comment by jgwerner** [comment]
@raygesualdo let us know if you would like us to help with this.

**Comment by raygesualdo** [comment]
Closed by #37.
