### ISSUE TITLE
Correct mismatch between eslint settings and styleguide

### ISSUE THREAD

**Issue by raygesualdo** [3Blades/react-frontend#23]
The eslint settings in the repo do not match the [3blades styleguide](https://github.com/3Blades/javascript). We need to either correct the eslint settings to reflect the styleguide (which would mean ejecting from create-react-app) or we need to change the styleguide to match the create-react-app eslint settings.

Another aspect to this would be looking into [prettier](https://github.com/jlongster/prettier) as a code style enforcement mechanism.

**Comment by jgwerner** [comment]
@raygesualdo we could use prettier but it seems to be in beta. i vote for changing the style guide to eslint settings. Code Climate and other code quality probably support standard eslint out of the box so those would be easier to test.
