### ISSUE TITLE
Integrate Sentry's error tracking library

### ISSUE THREAD

**Issue by raygesualdo** [3Blades/react-frontend#24]
We need to add Sentry's Raven.js library to the application. Documentation to do so is here: [https://docs.sentry.io/clients/javascript/install/](https://docs.sentry.io/clients/javascript/install/). The implementation should include Sentry optional settings for `release` and `environment`.

**Comment by jgwerner** [comment]
@raygesualdo we are using Sentry for our Python error tracking so using Sentry for our ReactJs project as well makes perfect sense.
