### ISSUE TITLE
Consider using react-storybook for UI development

### ISSUE THREAD

**Issue by raygesualdo** [3Blades/react-frontend#25]
[React Storybook](https://github.com/storybooks/react-storybook) is a great tool for developing UI elements in isolation. It also can serve as an effective component documentation tool. Let's look at getting this set up in the repo, specifically using the paradigm of having story files adjacent to the elements they relate to ([setup here](https://getstorybook.io/docs/react-storybook/basics/writing-stories#loading-stories-dynamically)). Addons that could be helpful include:

- [Host](https://github.com/philcockfield/storybook-host)
- [Knobs](https://github.com/storybooks/storybook-addon-knobs)
- [Info](https://github.com/storybooks/react-storybook-addon-info)

**Comment by jgwerner** [comment]
@raygesualdo I like this proposal, the fact that a lot of the elements can be created in a declarative way seems to be a good time saver.

**Comment by johngriebel** [comment]
@raygesualdo - What's the status of this? Can we close this issue?

**Comment by raygesualdo** [comment]
Yes. This was more of a discussion issue, but it's very out of date and I don't think we want to take the time to do this right now. I'll close it.
