### ISSUE TITLE
Update Webpack to v2

### ISSUE THREAD

**Issue by raygesualdo** [3Blades/react-frontend#26]
If/When we eject from the default create-react-app configuration, we should upgrade to Webpack 2 to benefit from its faster compile times and dead code elimination. The upgrade guide can be found here: https://webpack.js.org/guides/migrating/.

**Comment by jgwerner** [comment]
@raygesualdo agree, we are probably going to have to upgrade sooner o later, might as well be now!

**Comment by raygesualdo** [comment]
Closed by #37.
