### ISSUE TITLE
Avatar is removed when updating settings page

### ISSUE THREAD

**Issue by jgwerner** [3Blades/react-frontend#278]
After successfully uploading an Avatar, the user does receive a prompt stating that the Avatar has been added successfully. However, if the user were to re click the `Update` button, then the Avatar is removed from the user's profile.

This was tested in dev and green:

![avatar_error](https://user-images.githubusercontent.com/920170/31619454-930d3220-b262-11e7-9313-1b538d5387fa.gif)

**Comment by raygesualdo** [comment]
There is an bug in how the API is returning the payload from a user profile update. This has been recorded as an issue in 3Blades/app-backend#427.
