### ISSUE TITLE
Display Banner When User's Trial Will End Soon

### ISSUE THREAD

**Issue by johngriebel** [3Blades/react-frontend#311]
Part of 3blades/3blades#142

When a user's trial is about to expire, there should be a banner visible to the user reminding them. Which page(s) this banner should appear on is TBD.

**Comment by johngriebel** [comment]
Part of 3blades/3blades/#146.

**Comment by raygesualdo** [comment]
Closing since A. we're moving to a free tier model and B. we have #344.
