### ISSUE TITLE
New On-Boarding Form for new accounts using OAuth

### ISSUE THREAD

**Issue by jgwerner** [3Blades/react-frontend#326]
User workflow for On-Boarding for the Free Trial, also known as `Get Started` or `Free Trial` (we will call this CTA from this point forward):

1. User lands on our website. The CTA may be one of two options:
- Email next to CTA button
- Just CTA button
2. After user clicks on CTA
- Landing page with the sign in options using OAuth (Google or GitHub) or Local Account. 
- If OAuth option is selected, the user should confirm account access and then should see a form hosted by `app.3blades.ai` to confirm additional account details, in particular: First Name, Last Name, Company, Email (pre-populated), Password, Company Size, Role. It should be hosted by our app since the OAuth postback will ask for our app's domain.
- If local account option is selected, fields appear already in the landing page form. Additional information would be First Name, Last Name, Company, Email (pre-populated), Password, Company Size, Role.

Once confirmed the user should have access to the system. 

TBD as a separate issue: email to validate the user's email address to complete account activation.

**Comment by raygesualdo** [comment]
@jgwerner What's the action item here? 

Some thoughts:

- Step 2 seems really unhelpful. We can perhaps collect that information once the user is in the application, but requiring that - even if one can skip it - would add a lot of friction to the signup process. 
- We don't have anywhere to store Company, Company Size and Role ATM.
- We shouldn't need to validate email for SSO users. We're relying on the 3rd party for email verification.

**Comment by raygesualdo** [comment]
Closing since we're not going to add fields to the registration page.
