### ISSUE TITLE
Add notifications when user cannot start servers due to expired trial accounts or invalid accounts

### ISSUE THREAD

**Issue by jgwerner** [3Blades/react-frontend#328]
Update frontend to surface 402 errors telling the user they cannot spawn servers due to:

- Expired accounts
- Billing issues with paid subscription
- Ceiling for user server resource use

3blades/3blades#146

**Comment by johngriebel** [comment]
@jgwerner note that it is not the intention to create new notification objects in the database each time a user attempts to start a server in these circumstances, at least in my understanding.

**Comment by raygesualdo** [comment]
Since we're moving from the "trial" paradigm to a free tier, I'm going to close this issue and open up a new one that encompasses adding visual elements regarding a user's free tier status (upgrade button, use/limits on servers, use/limits on projects, etc.).
