### ISSUE TITLE
Unclear Notifications page in Account Settings

### ISSUE THREAD

**Issue by jgwerner** [3Blades/react-frontend#329]
It seems to me that we should have one notifications page, for all notifications. Right now it looks like there are two notifications pages. It's either a bug or we are waiting for a notifications settings page. If it's the latter, then we need to hide that item from the UI until it's ready.

If this section intends on just displaying notifications, then viewing "Notifications" from the `Account --> Settings --> Notifications` it doesn't make too much sense because of context. In this section, it would make more sense to have `Audit Logs`, if we were to support that moving forward.

Now the `Account --> Notifications` section looks like:

![screen shot 2017-10-29 at 9 13 05 am](https://user-images.githubusercontent.com/920170/32144207-afb44e44-bc8b-11e7-9c86-db164ad0eaf6.png)

The Notifications icon looks like:

![screen shot 2017-10-29 at 9 13 18 am](https://user-images.githubusercontent.com/920170/32144215-cd3686f8-bc8b-11e7-8cab-db0cb79984d9.png)

**Comment by johngriebel** [comment]
@jgwerner we're waiting for a notification settings page.

**Comment by jgwerner** [comment]
@jgriebel I’m that case we need to hide the link until we have the page.

**Comment by johngriebel** [comment]
Agreed.

**Comment by raygesualdo** [comment]
@jgwerner @johngriebel I don't know why you're not seeing settings there. This is what I get:

![image](https://user-images.githubusercontent.com/5465958/32169984-20e74a4a-bd49-11e7-8f4b-62e72da2d71e.png)

**Comment by roachmd** [comment]
<img width="1433" alt="screen shot 2017-10-30 at 8 12 22 am" src="https://user-images.githubusercontent.com/5784681/32170219-287f6746-bd4a-11e7-9251-a73cad9bff3b.png">


Using Chrome on Mac : Version 61.0.3163.100 (Official Build) (64-bit)
