### ISSUE TITLE
Unable to delete account from UI

### ISSUE THREAD

**Issue by jgwerner** [3Blades/react-frontend#331]
Users can't delete their accounts. 

![delete_account_bug](https://user-images.githubusercontent.com/920170/32145809-b9c5f6f8-bca4-11e7-94d5-54540d3b8ac3.gif)

**Comment by johngriebel** [comment]
@raygesualdo @jgwerner I did some preliminary investigating, and it looks like the "Delete Your Account" button doesn't actually send a request of any sort to app-backend. You'll note from the linked issue that there is a small bug to fix in app-backend for when such a request will be sent.
