### ISSUE TITLE
Integrate Segment to push usage data to multiple destinations

### ISSUE THREAD

**Issue by jgwerner** [3Blades/react-frontend#332]
Segment allows us to push data from the site to multple destinations, such as send data to [Appcues](https://www.appcues.com) for on-boarding, HubSpot analytics to track campaign performance, etc.. Segment would allow us to switch from Appcues to another solution down the work without changing the snippet.

There is an option to push data from Segment to Heap Analytics, but we can leave both for now while we evaluate options.

**Comment by raygesualdo** [comment]
Closing since we have #337 now.

**Comment by raygesualdo** [comment]
Accidentally closed issue instead of stale PR. Oops.
