### ISSUE TITLE
UI displays .nfs files under certain circumstances

### ISSUE THREAD

**Issue by jgwerner** [3Blades/react-frontend#356]
After creating or saving a file, an operating system file related to NFS shares is displayed in the UI. We should hide these files from view in the UI.

This is related to latest [PR to green](https://github.com/3Blades/react-frontend/pull/348/commits). Error can be replicated [with preview](https://deploy-preview-348--threeblades-webui-green.netlify.com) deployment. and am unable to replicate this in production, so it seems to be a new bug introduced with latest master branch. To replicate:

- Create or save a file
- Update file
- Navigate to Files section

![nfs_file_error](https://user-images.githubusercontent.com/920170/32407336-c1bbb6fa-c15d-11e7-801f-54827321cd2a.gif)

**Comment by johngriebel** [comment]
@jgwerner this is a backend issue.

**Comment by raygesualdo** [comment]
Closing now the we have 3blades/app-backend#508.
