### ISSUE TITLE
Require additional fields in registration form

### ISSUE THREAD

**Issue by jgwerner** [3Blades/react-frontend#358]
Our [registration form](https://app.3blades.io/auth/register) needs to require additional information so we can send it to third party systems such as our CRM. 

The registration form should require:

- Full Name
- Email
- Password
- Company Name
- Company Size
- Role
- Accept both Terms and Conditions and Privacy Policy

We should probably think of a way to easily change destination for POSTs using env vars to avoid unnecessary code changes in the future.

**Comment by johngriebel** [comment]
@jgwerner company info should be optional of course. I'm not sure what you mean by the last point.

**Comment by jgwerner** [comment]
@johngriebel I don't think it is a backend issue. The app shouldn't need to capture all the data above. It's purely for marketing automation and analysis purposes. Third party form services are difficult to configure with POSTs to external endpoints, hence the request to have something on the [app.3blades.ai](https://app.3blades.ai) domain.

The last point refers to the fact that we only ask for the user to accept Terms and Conditions. They should accept the privacy policy as well.

Here is an example from Intercom:

![intercom_enrollment_form](https://user-images.githubusercontent.com/920170/32410400-3e7b10fa-c195-11e7-92d3-923a4867def6.png)

**Comment by johngriebel** [comment]
Ah okay. By "last point" I mean the sentence below the bulleted list, but you explained that anyhow. 😀

**Comment by jgwerner** [comment]
@johngriebel I talked to @raygesualdo and have agreed to leave the form as-is, but update design. We will ask for additional user profile information as they get on-boarded and has to do with 3blades/3blades#162.

So the only update for this issue is to update:

- Accept both Terms and Conditions and Privacy Policy
