### ISSUE TITLE
FIX: Create A file : PR blue

### ISSUE THREAD

**Issue by roachmd** [3Blades/react-frontend#363]
FIX:

deploy-preview-359

Create a file in UI does not seem to work now.

![pr-prod-blue-create-a-file](https://user-images.githubusercontent.com/5784681/32461772-f03b6a86-c304-11e7-96a5-374461f39003.gif)

**Comment by raygesualdo** [comment]
Is this still an issue?

**Comment by raygesualdo** [comment]
@roachmd ^^^

**Comment by johngriebel** [comment]
@raygesualdo I've been able to create a file in blue. Closing the issue.
