### ISSUE TITLE
Pull Request coverage reports for all branches to upstream master branch

### ISSUE THREAD

**Issue by jgwerner** [3Blades/react-frontend#45]
When using fork, [Codecov](https://codecov.io/gh/3Blades/react-frontend) coverage reports are triggered only when creating a PR from master branch to master branch.

Please adjust codecov.yml so that coverage reports are displayed when creating PR's from working branch in fork to upstream master or from master in fork to upstream master.

> `upstream` denotes https://github.com/3blades/react-frontend

**Comment by raygesualdo** [comment]
This was fixed in #43. Forgot to tag it.
