### ISSUE TITLE
Handle messages when creating new server and starting server

### ISSUE THREAD

**Issue by jgwerner** [3Blades/react-frontend#69]
Servers that are created may not have an existing image. This is not necessarily an issue for customer facing UI at this point since Admins create the servers either with CLI Tools or with Back Office UI.

However, one of two scenarios may occur:

- Image does not exist and system returns an error
- Image exists but there is a `latest` update in registry

In either case, the error / status should be handled accordingly.

3blades/3blades#73

**Comment by johngriebel** [comment]
Image types will be selectable from a drop-down in the UI, so this is no longer applicable.
