### ISSUE TITLE
Project view error

### ISSUE THREAD

**Issue by jgwerner** [3Blades/react-frontend#79]
Once you create a project and then go to home (initial page), an error appears when trying to navigate back to the project.

![project_view_error](https://user-images.githubusercontent.com/920170/27336262-fc0d823e-559c-11e7-94bf-d4d53715cbf8.gif)

#90

**Comment by raygesualdo** [comment]
Was able to replicate with @roachmd. The links on the home scene are hardcoded for the `foo` user. I'll fix it.
