### ISSUE TITLE
Stopping a server that is in Running state returns error.

### ISSUE THREAD

**Issue by jgwerner** [3Blades/react-frontend#81]
After successfully creating and starting a Server, the user has the option to Stop the server. When attempting to stop a server in the Running state, the server returns an error.

![stop_server_error](https://user-images.githubusercontent.com/920170/27336848-cae26650-559e-11e7-8905-7d616db82fb1.gif)

#90

**Comment by raygesualdo** [comment]
This error will be fixed by 3Blades/docker-events#7. Closing this issue since no change is required in the react-frontend repo.
