### ISSUE TITLE
Not clear how to add server resource types or sizes

### ISSUE THREAD

**Issue by jgwerner** [3Blades/react-frontend#83]
When creating a new server resource, there are two options the user needs to select:

- Server size
- Server type

It's not clear where to add these new server resources. There should be an admin section to add these server types. Perhaps it's out of the scope of the react-frontend project, in any case, there should be a link to an Admin portal to add these server resources particularly for on-premises customers.

![server_resource](https://user-images.githubusercontent.com/920170/27342717-f6a9e85c-55ae-11e7-9d22-cafc7c892b94.gif)

Our legacy version has an Admin Console Link:

![legacy_admin](https://user-images.githubusercontent.com/920170/27343055-cf31cc08-55af-11e7-9218-8d09c6d2982e.gif)

#88

**Comment by jkp85** [comment]
@jgwerner This should be done with django admin, not implemented there though.

**Comment by jkp85** [comment]
Resource types are not managed inside db. Now we have only sizes in db. Types are hardcoded for the time being.

**Comment by jgwerner** [comment]
Yes, and I believe it should stay that way. Integration should be done as it was with our legacy version. Specifically, add a link to the react-frontend users that have the Admin role assigned to them, so they can navigate to Django based admin pages. Customized look and feel for admin pages is not a priority at this point.

**Comment by raygesualdo** [comment]
@jgwerner Not sure what the action item is here in regards to the react-frontend project.

**Comment by raygesualdo** [comment]
@jgwerner I'm going to close this issue since there's nothing actionable.
